const User = require('./database-models/User')
const UserPost = require('./database-models/User-Post')
const PostCategory = require('./database-models/Post-Category')
const Comment = require('./database-models/Comment')
const Admin = require('./database-models/Admin')
const AdminPost = require('./database-models/Admin-Post')